# Generated by Django 5.2.13 on 2026-04-13 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('profession', models.CharField(max_length=50, verbose_name='Профессия')),
                ('about', models.TextField(max_length=2000, verbose_name='Краткое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255, verbose_name='Компания')),
                ('position', models.CharField(max_length=255, verbose_name='Долдность')),
                ('start_year', models.IntegerField(verbose_name='Год начала')),
                ('end_year', models.IntegerField(verbose_name='Год окончания')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='web.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('speciality', models.CharField(max_length=100, verbose_name='Специальность')),
                ('admission_year', models.IntegerField(verbose_name='Год поступления')),
                ('graduation_year', models.IntegerField(verbose_name='Год окончания')),
                ('description', models.TextField(max_length=2000, verbose_name='Описание')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='web.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')], verbose_name='Уровень')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='web.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('link', models.URLField(max_length=500, unique=True)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='web.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='TechnologiesProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.profile')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.technologies')),
            ],
        ),
        migrations.AddField(
            model_name='technologies',
            name='profiles',
            field=models.ManyToManyField(related_name='technologies', through='web.TechnologiesProfiles', to='web.profile', verbose_name='Профили'),
        ),
    ]
