# Generated by Django 5.2.13 on 2026-04-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
