# Generated by Django 5.2.13 on 2026-04-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_education_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True, max_length=255, verbose_name='Аватар'),
        ),
    ]
